import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div>
      <div className="bg-gray-100">
        <header className="bg-black sticky top-0 z-30 w-full px-2 md:py-0  py-4  sm:px-4 shadow-xl">
          <div className="flex items-center justify-between mx-auto max-w-7xl">
            <div className='flex justify-center items-center gap-2'>
              <Image src={"/images/logo.jpg"} width="60px" height="60px" />
              <a href="#" className='max-w-[300px] md:max-w-full'>
                <span className="text-xl font-extrabold text-white">The Holy Cross Brewing Society</span>
              </a>
            </div>
            <div className="flex items-center space-x-1">
              <ul className="hidden space-x-2 md:inline-flex">
                <li>
                  <a href="#" className="px-2 py-2 font-semibold text-white rounded">
                    <div className="flex items-center justify-center gap-4 px-3 m-0">
                      <Image src={"/images/mail.svg"} width="24px" height="24px" />
                      <span>Contact Us</span>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="#" className="px-2 py-2 font-semibold text-white rounded">
                    <div className="flex items-center justify-center gap-4 px-3 m-0">
                      <Image src={"/images/direc.svg"} width="24px" height="24px" />
                      <span>Get Directions</span>
                    </div>
                  </a>
                </li>
              </ul>
              <div className="inline-flex md:hidden">
                <button className="flex-none px-2 ">
                  <Image src={"/images/hamburger.jpg"} width="64px" height="64px" />
                  <span className="sr-only">Open Menu</span>
                </button>
              </div>
            </div>
          </div>
        </header>

        <section className="p-4 mx-auto max-w-7xl">
          <div className="mx-auto font-sans h-[1024px]">
          </div>
        </section>
      </div>
    </div>
    // <div classNameName={styles.container}>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>

    //   <main classNameName={styles.main}>
    //     <h1 classNameName={styles.title}>
    //       Welcome to <a href="https://nextjs.org">Next.js!</a>
    //     </h1>

    //     <p classNameName={styles.description}>
    //       Get started by editing{' '}
    //       <code classNameName={styles.code}>pages/index.tsx</code>
    //     </p>

    //     <div classNameName={styles.grid}>
    //       <a href="https://nextjs.org/docs" classNameName={styles.card}>
    //         <h2>Documentation &rarr;</h2>
    //         <p>Find in-depth information about Next.js features and API.</p>
    //       </a>

    //       <a href="https://nextjs.org/learn" classNameName={styles.card}>
    //         <h2>Learn &rarr;</h2>
    //         <p>Learn about Next.js in an interactive course with quizzes!</p>
    //       </a>

    //       <a
    //         href="https://github.com/vercel/next.js/tree/canary/examples"
    //         classNameName={styles.card}
    //       >
    //         <h2>Examples &rarr;</h2>
    //         <p>Discover and deploy boilerplate example Next.js projects.</p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         classNameName={styles.card}
    //       >
    //         <h2>Deploy &rarr;</h2>
    //         <p>
    //           Instantly deploy your Next.js site to a public URL with Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>

    //   <footer classNameName={styles.footer}>
    //     <a
    //       href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //       target="_blank"
    //       rel="noopener noreferrer"
    //     >
    //       Powered by{' '}
    //       <span classNameName={styles.logo}>
    //         <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    //       </span>
    //     </a>
    //   </footer>
    // </div>
  )
}

export default Home
